name: Run My Composite Action

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use my composite action
        id: my-action  # <-- Add this so you can access outputs from this step
        uses: ./.github/actions/my-composite-action
        with:
          node-version: '18'

      - name: Display result
        run: 'echo Script Result: ${{ steps.my-action.outputs.script-result }}'

